### ISSUE TITLE
Разделение труда

### ISSUE THREAD

**Issue by dzhus** [archimag/archimag-lisp-overlay#9]
Зачем форкать весь lisp-оверлей, когда можно в нём держать только отличающиеся/новые ебилды?

**Comment by dzhus** [comment]
И неплохо бы отличия slime-archimag от slime переместить в отдельный модуль для slime, вместо нынешнего блокирующего апстрим ебилда.

**Comment by archimag** [comment]
> Зачем форкать весь lisp-оверлей, когда можно в нём держать только отличающиеся/новые ебилды?

А какая разница? Так просто проще.

> И неплохо бы отличия slime-archimag от slime переместить в отдельный модуль для slime

Не знаю как это сделать :(

**Comment by dzhus** [comment]
> какая разница?

Тебе приходится делать merge. У пользователя, если он подключает lisp и archimag-lisp, множатся записи в выдаче eix/emerge. Если не подключать lisp, а только archimag-lisp, то приходится зависеть от того, что ты своевременно сливаешь с мастером. Но это фиг с ним.

> Не знаю как это сделать :(

Там отличия только в том, что две команды добавлено, как сказано здесь http://restas.lisper.ru/ru/manual/slime.html?

**Comment by archimag** [comment]
> Тебе приходится делать merge.

Ну это ведь не проблема. Более важно, что я могу вносить изменения в основной репозиторий. Например, есть пакет puri и мой форк puri-unicode. Они не могут использоваться совместно или даже быть установленными совместно, поэтому я делаю virtual/puri и изменяю зависимости в других пакетах. Я не могу этого сделать в отдельном репозитории. Кроме того, есть ньюансы с eclass, которые должны быть в оверлее и не подхватываются из другого оверлея (во всяком случае, у меня не хотели, но я долго не вникал).

> Там отличия только в том, что две команды добавлено

Команды для RESTAS и реализованы отдельным модулем (https://github.com/archimag/restas/tree/master/slime). Но что бы они работали пришлось внести несколько изменений в оригинальный SLIME (например, простую функцию swank:object-source-location превратить в generic), который я и назвал slime-archimag. В оверлей, соответственно, пришлось добавить virtual/slime.
